
services:
  app:
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    ports:
      - "8081:8080"          # different external port to avoid clash with dev

  postgres:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_STAGING:-SuperSecretStagingPass!2025}

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD_STAGING:-RedisStagingPass!2025}