apiVersion: v1
kind: Service
metadata:
  name: cognitive-postgres-bank
  namespace: cognitive-bank
spec:
  type: ClusterIP
  selector:
    app: cognitive-postgres-bank
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
