apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-redis
  namespace: cognitive-bank
spec:
  podSelector:
    matchLabels:
      app: cognitive-redis-cache

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cognitive-banking-backend
      ports:
        - protocol: TCP
          port: 6379
