apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognitive-banking-backend
  namespace: cognitive-bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cognitive-banking-backend
  template:
    metadata:
      labels:
        app: cognitive-banking-backend
    spec:
      containers:
        - name: backend
          image: fulufhelom/cognitive-banking-application:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          # --------------------------
          # ENV VARIABLES FROM SECRETS
          # --------------------------
          env:
            # Spring Boot DB
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://cognitive-postgres-bank:5432/cognitive_bank
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cognitive-backend-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cognitive-backend-secrets
                  key: DB_PASSWORD

            # Redis
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: cognitive-backend-secrets
                  key: REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: cognitive-backend-secrets
                  key: REDIS_PORT
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cognitive-backend-secrets
                  key: REDIS_PASSWORD

            # Application settings
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: cognitive-backend-secrets
                  key: SPRING_PROFILES_ACTIVE
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: cognitive-backend-secrets
                  key: SERVER_PORT

          # --------------------------
          # LIVENESS & READINESS PROBES
          # --------------------------
          readinessProbe:
            httpGet:
              path: /api/cognitive/bank/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/cognitive/bank/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          # --------------------------
          # RESOURCES
          # --------------------------
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
