apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognitive-banking-backend
  namespace: cognitive-bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cognitive-banking-backend
  template:
    metadata:
      labels:
        app: cognitive-banking-backend
    spec:
      containers:
        - name: backend
          image: fulufhelom/cognitive-banking-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          # --------------------------
          # ENV VARIABLES FROM CONFIGMAP + SECRET
          # --------------------------
          envFrom:
            - configMapRef:
                name: cognitive-backend-config
            - secretRef:
                name: cognitive-backend-secrets

          # --------------------------
          # LIVENESS & READINESS PROBES
          # --------------------------
          readinessProbe:
            httpGet:
              path: /api/cognitive/bank/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/cognitive/bank/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          # --------------------------
          # RESOURCES
          # --------------------------
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
