apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-scrape-config
  namespace: cognitive-bank
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'cognitive-backend'
        static_configs:
          - targets: ['cognitive-banking-backend:80']
        metrics_path: /actuator/prometheus
