apiVersion: v1
kind: Secret
metadata:
  name: cognitive-backend-secrets
  namespace: cognitive-bank
type: Opaque
stringData:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "cognitive_bank"
  DB_USERNAME: "desta"
  DB_PASSWORD: "C0g1n1tiv5B@nk"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "redispass123"
