apiVersion: v1
kind: Service
metadata:
  name: cognitive-backend
  namespace: cognitive-os
spec:
  selector:
    app: cognitive-banking-backend
  ports:
    - protocol: TCP
      port: 8000       # Cluster port
      targetPort: 8000 # Pod container port
  type: LoadBalancer
