apiVersion: v1
kind: Service
metadata:
  name: cognitive-banking-backend
  namespace: cognitive-bank
spec:
  selector:
    app: cognitive-banking-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32087
  type: NodePort