apiVersion: v1
kind: Service
metadata:
  name: cognitive-banking-backend
  namespace: cognitive-bank
  labels:
    app: cognitive-banking-backend
spec:
  selector:
    app: cognitive-banking-backend
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32087
      name: http