apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-network-policy
  namespace: cognitive-bank
spec:
  podSelector:
    matchLabels:
      app: cognitive-postgres-bank
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cognitive-banking-backend
      ports:
        - protocol: TCP
          port: 5432
  policyTypes:
    - Ingress