apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network-policy
  namespace: cognitive-bank
spec:
  podSelector:
    matchLabels:
      app: cognitive-redis-cache
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cognitive-banking-backend
      ports:
        - protocol: TCP
          port: 6379
  policyTypes:
      - Ingress