apiVersion: v1
kind: Service
metadata:
  name: cognitive-redis-cache
  namespace: cognitive-bank
spec:
  selector:
    app: cognitive-redis-cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP